# Generated by Django 3.2.16 on 2025-11-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='mint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.mint'),
        ),
    ]
