# Generated by Django 3.2.16 on 2025-11-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20251107_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banknote',
            options={'verbose_name': 'банкнота', 'verbose_name_plural': 'банкнот(ы)'},
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'монета', 'verbose_name_plural': 'монет(ы)'},
        ),
        migrations.AlterField(
            model_name='banknote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='denomination',
            field=models.CharField(max_length=50, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='denomination',
            field=models.CharField(max_length=50, verbose_name='Номинал'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='Год'),
        ),
    ]
