# Generated by Django 3.2.16 on 2025-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20251107_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=50),
        ),
    ]
