# Generated by Django 3.2.16 on 2025-11-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_coin_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banknote',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.material'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mint'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='В граммах', max_digits=8, null=True),
        ),
    ]
